Actions | fix 1.2.2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,17 +32,39 @@ jobs:
       - name: install dependencies
         run: pip install -r requirements.txt
 
-      - name: run tests
-        run: pytest --alluredir=allure-results
-      - name: all_tests
-        if: "github.event.inputs.deployment_target == 'all_tests'"
-        run: pytest
-      - name: smoke_tests
-        if: "github.event.inputs.deployment_target == 'smoke_tests'"
-        run: pytest -m smoke
-      - name: regression_tests
-        if: "github.event.inputs.deployment_target == 'regression_tests'"
-        run: pytest -m regression
+      - name: Run tests
+        run: |
+          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
+            case ${{ github.event.inputs.deployment_target }} in
+              all_tests)
+                pytest --alluredir=allure-results
+                ;;
+              smoke_tests)
+                pytest -m smoke --alluredir=allure-results
+                ;;
+              regression_tests)
+                pytest -m regression --alluredir=allure-results
+                ;;
+              *)
+                echo "Invalid target selected."
+                exit 1
+                ;;
+            esac
+          else
+            pytest --alluredir=allure-results
+          fi
+
+#      - name: run tests
+#        run: pytest --alluredir=allure-results
+#      - name: all_tests
+#        if: "github.event.inputs.deployment_target == 'all_tests'"
+#        run: pytest
+#      - name: smoke_tests
+#        if: "github.event.inputs.deployment_target == 'smoke_tests'"
+#        run: pytest -m smoke
+#      - name: regression_tests
+#        if: "github.event.inputs.deployment_target == 'regression_tests'"
+#        run: pytest -m regression
 
       - name: Get Allure history
         uses: actions/checkout@v2
